### Idle configuration
#
# swayidle (using swaddle for DBUS inhibition)

set $lockscreen swaylock --daemonize

exec_always --no-startup-id swaddle &
exec swayidle -w \
         timeout 300 $lockscreen \
         timeout 360 'systemctl suspend' \
         before-sleep $lockscreen

# hypridle (does listen to DBUS)
# (requires hypridle to be installed, obviously)
# exec hypridle
