### Input configuration

input type:keyboard {
  repeat_delay 270
  repeat_rate 30
}

input type:touchpad {
  natural_scroll enabled
  tap enabled
  dwt disabled
}

#enable numlock by default
input type:keyboard xkb_numlock enabled
