set $refresh_bar true
set $lockscreen swaylock
set $screenshot slurp | grim -g - - | wl-copy
set $exit_cmd "swaynag -t warning -m 'Exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'"
set $zoomer pkill -x woomer || woomer

include ../i3_sway/keybinds.conf

bindsym XF86MonBrightnessUp exec brightnessctl s -- +10% &
bindsym XF86MonBrightnessDown exec brightnessctl s -- -10% &

# move tiling windows via drag & drop by left-clicking
# anywhere into the window while holding the floating modifier.
tiling_drag enable
