# # styling:
#   gaps inner 10
#   gaps outer 10
#
#   corner_radius 5
#
#   # idle dimming
#     default_dim_inactive 0.2
#
#   # shadows
#     shadows enable
#     shadow_color #0000007f
#
#   # opacity
#     for_window [class=".*"] opacity $opacity
#     for_window [app_id=".*"] opacity $opacity
#
#   # blurs
#     blur enable
#     blur_passes 4
#     blur_radius 4
#     blur_saturation 0.8
#
#   # colors:                   border  background  text    indicator child_border
#     client.focused            #8940a5 #4c245c     #eeeeee #9847b8   #8940a5
#     client.focused_inactive   #611d7c #1e0e25     #aaaaaa #8940a5   #611d7c
#     client.unfocused          #813d9c #1e0e25     #aaaaaa #8940a5   #813d9c
#     client.urgent             #e87d89 #f4bec4     #ffffff #ec939d   #e87d89
#     client.placeholder        #453b5e #453b5e     #453b5e #453b5e   #453b5e
#
#   # title bars
#     # titlebar_padding 1
#     # titlebar_border_thickness 0
#
#     default_border pixel 2
#
#     title_align center
#
#     font Kode Mono 12
#

include ../i3_sway/layout.conf
