for_window [title="."] opacity set 0.97

animation_duration_ms 250

default_dim_inactive 0.1

titlebar_separator disable

scratchpad_minimize enable

blur enable
blur_xray disable
blur_radius 4

shadows enable

corner_radius 9

for_window [title=".*"] border none
