set $refresh_bar killall -SIGUSR1 i3status
set $lockscreen betterlockscreen -l
set $screenshot selx | xargs sxot -g | ffmpeg -i - -f image2pipe -vcodec png - | xclip -selection clipboard -target image/png
set $exit_cmd "i3-nagbar -t warning -m 'Exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
set $zoomer pkill -x boomer || boomer

set $menu rofi -show drun

include ../i3_sway/keybinds.conf

# move tiling windows via drag & drop by left-clicking into the title bar,
# or left-clicking anywhere into the window while holding the floating modifier.
tiling_drag modifier titlebar
