alias ll='ls -l'
alias la='ls -lA'
alias lld='ll -d */'

alias cat='bat -P'
alias less='bat'

alias gdb='gdb -q'

if [ $XDG_SESSION_TYPE = "tty" ]; then
  alias fastfetch='fastfetch --load-config $HOME/.config/fastfetch/tty.jsonc';
elif [ $TERM = "xterm-kitty" ] || [ $TERM = "xterm-ghostty" ]; then
  alias fastfetch='fastfetch --logo-type kitty-direct';
fi;
